import type { TemplateDefinition } from "@/lib/types";

export const TEMPLATE_VERSION = "1.0.0";

export const SOFTWARE_DEV_TEMPLATE: TemplateDefinition = {
  version: TEMPLATE_VERSION,
  sections: [
    {
      title: "1. Requirements",
      items: [
        "Understand the problem",
        "Define the goal/objective",
        "Identify target users",
        "Define user roles",
        "List core features",
        "List non-functional requirements",
        "NFR: Performance",
        "NFR: Security",
        "NFR: Scalability",
        "NFR: Availability",
        "Define MVP scope",
        "Write acceptance criteria",
        "Identify edge cases",
      ],
    },
    {
      title: "2. Planning",
      items: [
        "Break requirements into tasks",
        "Prioritize tasks",
        "Create milestones",
        "Estimate development time",
        "Identify technical risks",
        "Decide what can be automated",
      ],
    },
    {
      title: "3. Architecture",
      items: [
        "Choose frontend technology",
        "Choose backend technology",
        "Choose database",
        "Design system architecture",
        "Define frontend ↔ backend communication",
        "Define authentication/authorization",
        "Define file/storage requirements",
        "Define third-party integrations",
        "Define deployment architecture",
      ],
    },
    {
      title: "4. UI/UX",
      items: [
        "Create user flows",
        "Create wireframes",
        "Design pages/screens",
        "Design reusable components",
        "Define responsive behavior",
        "Define loading states",
        "Define empty states",
        "Define error states",
        "Define success states",
      ],
    },
    {
      title: "5. Project Setup",
      items: [
        "Create Git repository",
        "Initialize project",
        "Configure package manager",
        "Configure TypeScript",
        "Configure ESLint",
        "Configure formatting",
        "Configure environment variables",
        "Create .env.example",
        "Create project structure",
        "Add README",
        "Configure Git hooks if needed",
      ],
    },
    {
      title: "6. Database",
      items: [
        "Design entities",
        "Create database schema",
        "Define relationships",
        "Add indexes",
        "Create migrations",
        "Add seed data",
        "Configure database connection",
        "Test CRUD operations",
      ],
    },
    {
      title: "7. Backend",
      items: [
        "Create API structure",
        "Implement authentication",
        "Implement authorization",
        "Implement CRUD APIs",
        "Add validation",
        "Add error handling",
        "Add logging",
        "Add rate limiting if needed",
        "Add API documentation",
        "Handle transactions",
        "Handle background jobs if needed",
      ],
    },
    {
      title: "8. Frontend",
      items: [
        "Build layouts",
        "Build pages",
        "Build reusable components",
        "Connect APIs",
        "Implement forms",
        "Implement validation",
        "Implement authentication UI",
        "Implement loading states",
        "Implement error handling",
        "Implement responsive design",
        "Handle permissions/roles",
      ],
    },
    {
      title: "9. Integrations",
      items: [
        "Payment provider",
        "Email provider",
        "OAuth/social login",
        "File storage",
        "Maps",
        "AI/LLM",
        "Analytics",
        "Other external APIs",
      ],
    },
    {
      title: "10. Testing",
      items: [
        "Unit: Utility functions",
        "Unit: Business logic",
        "Unit: Services",
        "Integration: API endpoints",
        "Integration: Database operations",
        "Integration: Authentication",
        "Integration: External integrations",
        "E2E: Signup",
        "E2E: Login",
        "E2E: Main user flow",
        "E2E: CRUD flow",
        "E2E: Logout",
        "E2E: Important error scenarios",
        "Test edge cases",
        "Test permissions",
        "Test invalid inputs",
        "Test failure scenarios",
        "Test mobile/responsive UI",
      ],
    },
    {
      title: "11. Security",
      items: [
        "Validate user input",
        "Secure authentication",
        "Secure cookies/tokens",
        "Password hashing",
        "Authorization checks",
        "Protect APIs",
        "Prevent SQL injection",
        "Prevent XSS",
        "Configure CORS",
        "Protect secrets",
        "Add rate limiting",
        "Review dependencies",
        "Security audit",
      ],
    },
    {
      title: "12. Performance",
      items: [
        "Optimize database queries",
        "Add appropriate indexes",
        "Optimize API responses",
        "Add caching where useful",
        "Optimize frontend bundles",
        "Optimize images",
        "Lazy load where appropriate",
        "Check Core Web Vitals",
        "Load test important APIs",
      ],
    },
    {
      title: "13. CI/CD",
      items: [
        "Create CI workflow",
        "Install dependencies",
        "Run lint",
        "Run type checking",
        "Run tests",
        "Build application",
        "Run E2E tests",
        "Build Docker image if needed",
        "Push deployment artifact/image",
        "Deploy automatically",
        "Configure staging environment",
        "Configure production environment",
      ],
    },
    {
      title: "14. Infrastructure / Cloud",
      items: [
        "Choose hosting",
        "Configure domain",
        "Configure DNS",
        "Configure SSL/HTTPS",
        "Configure database",
        "Configure storage",
        "Configure networking",
        "Configure secrets",
        "Configure monitoring",
        "Configure backups",
        "Configure scaling",
      ],
    },
    {
      title: "15. Production Readiness",
      items: [
        "Production environment variables",
        "Database migrations",
        "Backup strategy",
        "Logging",
        "Error tracking",
        "Monitoring",
        "Health checks",
        "Alerts",
        "Rollback strategy",
        "Disaster recovery plan",
      ],
    },
    {
      title: "16. Documentation",
      items: [
        "README",
        "Local setup instructions",
        "Environment variables documentation",
        "API documentation",
        "Architecture documentation",
        "Deployment instructions",
        "Troubleshooting guide",
        "Contribution guide",
      ],
    },
    {
      title: "17. Release",
      items: [
        "Final QA",
        "Run complete test suite",
        "Fix critical bugs",
        "Security review",
        "Performance check",
        "Deploy to staging",
        "Test staging",
        "Deploy production",
        "Verify production",
        "Monitor after release",
      ],
    },
    {
      title: "18. Maintenance",
      items: [
        "Monitor errors",
        "Monitor performance",
        "Fix production bugs",
        "Update dependencies",
        "Review security vulnerabilities",
        "Optimize infrastructure costs",
        "Add requested features",
        "Refactor technical debt",
        "Maintain documentation",
      ],
    },
  ],
};

export function getTemplateDefinition(): TemplateDefinition {
  return SOFTWARE_DEV_TEMPLATE;
}
